-- Superseded on 2026-09-17.
-- The production schema was rebuilt and is now tracked by the 20260916/20260917
-- migrations in this directory. This placeholder intentionally remains so older
-- clones do not replay the obsolete prototype schema.
